FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

# CHOKIDAR_USEPOLLING нужен для корректного watch на Docker Desktop (Mac/Windows)
ENV CHOKIDAR_USEPOLLING=true

CMD ["sh", "-c", "npm run seed && npm run seed:mock && npm run start:dev"]
